### ISSUE TITLE
Story Completion Prerequisites don't seem to save

### ISSUE THREAD

**Issue by starlight54** [Meth962/FFX2SaveEditor#1]
I did a little debugging on this. Essentially they get read from the beginning of the stream since it copies out some bytes from the beginning

```
byte[] work = br.ReadBytes(0x222c);
...
byte b = work[f.Address];
```

But then saved to a location with the story offset when the double click event triggers, ultimately

```
bw.BaseStream.Seek(storyOffset + offset, SeekOrigin.Begin);
bw.Write(value);
```

I'm guessing the first location is actually right, since it picked up which prerequisites I'd met and hadn't met, which would be quite the coincidence if it read from the wrong place!

My save did load either way, and I didn't look around too much for anything broken, which location is actually correct? It seems to me that either the read or write just need updating, but I'm not sure which!

Just tried to move the read for prerequisites on by the story offset, but then it doesn't match what I've actually done. I'm on PC as well if that matters for the save format :)

**Comment by Meth962** [comment]
Thanks for finding this. Looks like a few bugs when I went to debug it. Fixed it! I think...

FYI, 0x222c - 0x622c is 0x4000 bytes of Story flags (only).
The prerequisite flags are sporadically located throughout 0x200 - 0xf00. You can see these listed in the GameInfo.cs class.

The bug was just as you were describing. I must have added Prerequisites much later to the app and didn't notice how it was trying to read those flags from the story location offset and not just the beginning of the file.

I double checked some of the flags like getting all Squatter Monkeys and such. I was confused because most of the Shinra placing spheres flags were off. I'm wondering if the game clears them in a later part of the game, but other than this, it looks good.

Checked in and new release!

**Comment by starlight54** [comment]
Awesome, cheers dude, I forgot to speak to the Kilika camera man in Chapter 1 so I used it for that :) Fix looks good to me.
